version: '3'
services:
    php-fpm:
        volumes:
            - ./:/var/www/html
            - ./.docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/local.ini:ro
        environment:
            APP_ENV: 'development'

    scheduler:
        volumes:
            - ./:/var/www/html

    queuer:
        volumes:
            - ./:/var/www/html

    webserver:
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./:/var/www/html
            - .docker/webserver/nginx.conf:/etc/nginx/conf.d/nginx.conf

    db:
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: laravel-react-admin
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ~/.laravel-react-admin-data:/var/lib/mysql
