version: '3'
services:
    php-fpm:
        environment:
            APP_ENV: 'production'

    webserver:
        ports:
            - '80:80'
            - '443:443'

    db:
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: laravel-react-admin
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ~/.laravel-react-admin-data:/var/lib/mysql

    db-admin:
        volumes:
            - ~/.laravel-react-admin-db-admin/sessions:/sessions
        environment:
            PMA_HOST: laravel-react-admin-db
            PMA_PORT: 3306
